% DIST_MATRIX_INTERVAL_ITERATOR  Computes pairwise Ca distance matrices for all interval pairs.
%
% Input:
%   ds - Data structure with coupled interval lists, organism folder paths, and PDB paths
%
% Output:
%   ds - Updated data structure; for each organism and interval, the field
%        ds.crnt_<organism>_<interval>_int_zero_dist_mat is populated with the
%        Ca distance matrix between the full reference protein and the interval-aligned
%        comparison structure. Degron intervals use the prefix '_deg_'.
%
% Reads _int_tx.pdb files generated by create_interval_pymol_files and PyMOL.
function ds = dist_matrix_interval_iterator(ds)
    load('folder_paths.mat');
    try
        crnt_zero_pdb_path = ds.(['crnt_' ds.zero_organism '_pdb_path']);
        crnt_zero_pdb = pdbread(crnt_zero_pdb_path);
        zero_intervals = ds.(['crnt_' ds.zero_organism '_intervals']);
        zero_degs = ds.(['crnt_' ds.zero_organism '_degrons_intervals']);
        number_of_zero_intervals = length(zero_intervals);
        number_of_zero_degs = length(zero_degs);
    catch Error
        return
    end
    %% non degron regions
    for k = 1: length(organism_list)
        crnt_organism = organism_list{k};
        %collecting intervals
        try
            crnt_organism_intervals = ds.(['crnt_' crnt_organism '_intervals']);
        catch Error
            continue
        end
        crnt_prot_id = ds.(['crnt_' crnt_organism '_protein_id']);
        for t = 1: number_of_zero_intervals
            crnt_interval = crnt_organism_intervals{t};
            crnt_folder_path = ds.(['crnt_' crnt_organism '_folder_path']);
            if strcmp(crnt_interval, ds.nan_interval) %-1--1 case
                continue
            end
            try
                crnt_interval_pdb_path = [crnt_folder_path crnt_prot_id '_' crnt_interval '_int_tx.pdb'];
                crnt_interval_pdb = pdbread(crnt_interval_pdb_path);
                dist_matrix = get_dist_mat2(crnt_zero_pdb, crnt_interval_pdb, ds.default_chain, ds.default_chain);
                ds.(['crnt_' crnt_organism '_' crnt_interval '_int_zero_dist_mat']) = dist_matrix;
            catch Error
                continue
            end
        end
        %% degron regions
        try
        crnt_organism_degs_intervals = ds.(['crnt_' crnt_organism '_degrons_intervals']);
        catch Error
            continue
        end
        for s = 1: number_of_zero_degs
            crnt_degs_interval = crnt_organism_degs_intervals{s};
            try
                crnt_deg_interval_pdb_path = [crnt_folder_path crnt_prot_id '_deg_' crnt_degs_interval '_int_tx.pdb'];
                crnt_deg_interval_pdb = pdbread(crnt_deg_interval_pdb_path);
                dist_matrix = get_dist_mat2(crnt_zero_pdb, crnt_deg_interval_pdb, ds.default_chain, ds.default_chain);
                ds.(['crnt_' crnt_organism '_deg_' crnt_degs_interval '_int_zero_dist_mat']) = dist_matrix;
            catch Error
                continue
            end
        end     
    end
end