% GET_DIST_MATRIX  Computes Ca pairwise distance matrices between the reference and each organism.
%
% Input:
%   ds - Data structure with PDB paths and organism list
%
% Output:
%   ds - Updated data structure; ds.crnt_<organism>_zero_dist_matrix populated for each
%        organism with a valid globally-aligned structure file (_tx.pdb).
%        Organisms with missing or unreadable structure files are skipped silently.
%
% Uses globally-aligned transformed PDB files (_tx.pdb) generated by PyMOL.
function ds = get_dist_matrix(ds)
    pdb_zro_organism = pdbread(ds.(['crnt_' ds.zero_organism '_pdb_path']));
    for i = 1: ds.number_of_organisms
        crnt_organism = ds.organism_list{i};
        try
            crnt_pdb_path = ds.(['crnt_' crnt_organism '_pdb_path']);
            crnt_pdbtx_path = [crnt_pdb_path(1:end-4) '_tx.pdb'];
            pdb_crnt_organism = pdbread(crnt_pdbtx_path);
            if isempty(pdb_crnt_organism)
                continue
            end
        catch
            pdb_crnt_organism  = 'NA';
            continue
        end
        % get carbon alpha matrices
        dist_matrix = get_dist_mat2(pdb_zro_organism, pdb_crnt_organism, ds.default_chain, ds.default_chain);
        ds.(['crnt_' crnt_organism '_zero_dist_matrix']) = dist_matrix;
    end
end

